package messages

// SendMessageRequest is the body for POST /messages.
//
// ClientMessageID is required, not optional — it's generated by the
// sending device and is what makes a retried send safe (see the
// unique index comment in migration 000006). A client that doesn't
// generate one loses that safety net entirely, so it's not treated as
// optional here.
//
// Body is plaintext for now — Week 5 is deliberately plaintext-first
// (see migration 000006's comment). This field's meaning will change
// once Week 6 adds real encryption (the client will send ciphertext
// instead), but the field itself likely won't need to.
type SendMessageRequest struct {
	ConversationID  string `json:"conversation_id" binding:"required"`
	ClientMessageID string `json:"client_message_id" binding:"required"`
	Body            string `json:"body" binding:"required"`
}

// MessageResponse confirms the message was stored (or, for a retried
// send with the same client_message_id, echoes back the original).
type MessageResponse struct {
	ID              string `json:"id"`
	ConversationID  string `json:"conversation_id"`
	SenderID        string `json:"sender_id"`
	ClientMessageID string `json:"client_message_id"`
	MessageType     string `json:"message_type"`
	Body            string `json:"body"`
	CreatedAt       string `json:"created_at"`
}

// ListMessagesQuery binds GET /messages/:conversationId's query
// parameters. Limit is intentionally clamped, not rejected, if out of
// range — a client asking for too many/too few is a minor client-side
// mistake, not something worth a 400 for. BeforeMessageID is optional
// cursor-based pagination: "give me messages older than this one,"
// for loading earlier history.
type ListMessagesQuery struct {
	Limit           int    `form:"limit"`
	BeforeMessageID string `form:"before_message_id"`
}

// ListMessagesResponse is the body for GET /messages/:conversationId.
type ListMessagesResponse struct {
	Messages []MessageListItem `json:"messages"`
}

// MessageListItem is one message as seen by the recipient fetching
// it — Status reflects THIS device's delivery status for THIS
// message, which the act of fetching may itself have just updated
// (sent -> delivered). See Service.ListMessages.
type MessageListItem struct {
	ID          string `json:"id"`
	SenderID    string `json:"sender_id"`
	MessageType string `json:"message_type"`
	Body        string `json:"body"`
	Status      string `json:"status"`
	CreatedAt   string `json:"created_at"`
}
